config:
  task_type: "col_dense_retriever"
  (): LLM4IR.trainer.colmodel_training.ColModelTrainingConfig
  output_dir: !path ../../../models/col-qwen2vl_128-0612
  processor:
    (): LLM4IR.utils.transformers_wrappers.AllPurposeWrapper
    class_to_instanciate: !ext LLM4IR.models.ColQwen2Processor
    pretrained_model_name_or_path:  "./model/Qwen2-VL-2B-Instruct"
    num_image_tokens: 2048
    # max_length: 50
  trainer : !ext LLM4IR.trainer.ContrastiveTrainer
  collator: !ext LLM4IR.collators.VisualRetrieverCollator
  model:
    (): LLM4IR.utils.transformers_wrappers.AllPurposeWrapper
    class_to_instanciate: !ext LLM4IR.models.ColQwen2
    pretrained_model_name_or_path: "./model/Qwen2-VL-2B-Instruct"
    torch_dtype:  !ext torch.bfloat16
    use_cache: false
    attn_implementation: "flash_attention_2"
#    device_map: "auto"
#    quantization_config:
#      (): transformers.BitsAndBytesConfig
#      load_in_4bit: true
#      bnb_4bit_quant_type: "nf4"
#      bnb_4bit_compute_dtype:  "bfloat16"
#      bnb_4bit_use_double_quant: true

  dataset_loading_func: !ext LLM4IR.dataset.dataset_transformation.load_train_set_detailed
  eval_dataset_loader: !import ../data/beir_debug_data.yaml

  # max_length: 50
  use_example: False
  run_train: True
  run_eval: True

  # pretrained_peft_model_name_or_path: './models/qwen2-col_dense-0428-epoch3'

  loss_func:
    (): LLM4IR.loss.late_interaction_losses.ColbertLoss

  tr_args:
    (): transformers.training_args.TrainingArguments
    output_dir: null
    overwrite_output_dir: true
    num_train_epochs: 1
    per_device_train_batch_size: 8
    gradient_checkpointing: true
    gradient_checkpointing_kwargs: { "use_reentrant": false }
    # gradient_checkpointing: true
    # 6 x 8 gpus = 48 batch size
    # gradient_accumulation_steps: 4
    per_device_eval_batch_size: 8
    eval_strategy: "steps"
    dataloader_num_workers: 8
    # bf16: true
    save_steps: 500
    logging_steps: 10
    eval_steps: 500
    warmup_steps: 100
    learning_rate: 3e-4
    save_total_limit: 1
    # resume_from_checkpoint: true
    # optim: "paged_adamw_8bit"
    # wandb logging
    run_name: "col-qwen2vl_128-train"
    report_to: "wandb"

  peft_config:
    (): peft.LoraConfig
    r: 32
    lora_alpha: 32
    lora_dropout: 0.1
    init_lora_weights: "gaussian"
    bias: "none"
    task_type: "FEATURE_EXTRACTION"
    target_modules: ["q_proj", "k_proj", "v_proj", "o_proj", "down_proj", "gate_proj", "up_proj", "lm_head"]
