config:
  (): colpali_engine.trainer.colmodel_training.ColModelTrainingConfig
  output_dir: !path ../../../models/colqwen2-sparse-test0202
  processor:
    (): colpali_engine.utils.transformers_wrappers.AllPurposeWrapper
    class_to_instanciate: !ext colpali_engine.models.SparseQwen2Processor
    pretrained_model_name_or_path:  "./model/Qwen2-VL-2B-Instruct"
    num_image_tokens: 2048
    # max_length: 50
  model:
    (): colpali_engine.utils.transformers_wrappers.AllPurposeWrapper
    class_to_instanciate: !ext colpali_engine.models.SparseQwen2
    pretrained_model_name_or_path: "./model/Qwen2-VL-2B-Instruct"
    torch_dtype:  !ext torch.bfloat16
    use_cache: false
    attn_implementation: "flash_attention_2"
#    device_map: "auto"
#    quantization_config:
#      (): transformers.BitsAndBytesConfig
#      load_in_4bit: true
#      bnb_4bit_quant_type: "nf4"
#      bnb_4bit_compute_dtype:  "bfloat16"
#      bnb_4bit_use_double_quant: true

  dataset_loading_func:
    (): colpali_engine.utils.dataset_transformation.load_mbeir_train_set
    mbeir_data_dir: !path '/data2/zhh_data/M-BEIR/'
    query_instruct_path: 'instructions/query_instructions.tsv'

    # train_query_data_path: 'query/train/mbeir_webqa_train.jsonl'
    # train_cand_pool_data_path: 'cand_pool/global/mbeir_union_train_cand_pool.jsonl'

    # val_query_data_path: 'query/val/mbeir_webqa_task1_val.jsonl'
    # val_cand_pool_data_path: 'cand_pool/global/mbeir_union_val_cand_pool.jsonl'

    train_query_data_path: 'query/train/mbeir_mscoco_train.jsonl'
    train_cand_pool_data_path: 'cand_pool/global/mbeir_union_train_cand_pool.jsonl'

    val_query_data_path: 'query/val/mbeir_mscoco_task3_val.jsonl'
    val_cand_pool_data_path: 'cand_pool/global/mbeir_union_val_cand_pool.jsonl'

    # (): colpali_engine.utils.dataset_transformation.load_beir_train_set
    # beir_data_dir: !path '/data2/zhh_data/BEIR/'
    # train_qrels_data_path : 'hotpotqa/qrels/train.tsv'
    # dev_qrels_data_path : 'hotpotqa/qrels/dev.tsv'
    # query_data_path: 'hotpotqa/queries.jsonl'
    # cand_pool_data_path: 'hotpotqa/corpus.jsonl'
    
  eval_dataset_loader: !import ../data/hotpotqa_data.yaml
  # max_length: 50
  use_example: False
  run_eval: True
  pretrained_peft_model_name_or_path: './models/colqwen2-sparse-test0202'
  run_train: False
  loss_func:
    (): colpali_engine.loss.sparse_encoder_losses.SparsePairwiseFlopsLoss
  tr_args:
    (): transformers.training_args.TrainingArguments
    output_dir: null
    overwrite_output_dir: true
    num_train_epochs: 1
    per_device_train_batch_size: 8
    gradient_checkpointing: true
    gradient_checkpointing_kwargs: { "use_reentrant": false }
    # gradient_checkpointing: true
    # 6 x 8 gpus = 48 batch size
    # gradient_accumulation_steps: 4
    per_device_eval_batch_size: 8
    eval_strategy: "steps"
    dataloader_num_workers: 4
    # bf16: true
    save_steps: 500
    logging_steps: 10
    eval_steps: 100
    warmup_steps: 100
    learning_rate: 3e-4
    save_total_limit: 1
    # resume_from_checkpoint: true
    # optim: "paged_adamw_8bit"
    # wandb logging
    # wandb_project: "sparse_qwen2"
    run_name: "sparse_qwen2-train"
    report_to: "wandb"

  peft_config:
    (): peft.LoraConfig
    r: 32
    lora_alpha: 32
    lora_dropout: 0.1
    init_lora_weights: "gaussian"
    bias: "none"
    task_type: "FEATURE_EXTRACTION"
    target_modules: '(.*(model).*(down_proj|gate_proj|up_proj|k_proj|q_proj|v_proj|o_proj).*$|.*(lm_head).*$)'
    # target_modules: '(.*(model).*(down_proj|gate_proj|up_proj|k_proj|q_proj|v_proj|o_proj).*$|.*(custom_text_proj).*$)'
    # target_modules: '(.*(language_model).*(down_proj|gate_proj|up_proj|k_proj|q_proj|v_proj|o_proj).*$|.*(custom_text_proj).*$)'

