config:
  task_type: "point_reranker"
  (): LLM4IR.trainer.colmodel_training.ColModelTrainingConfig
  output_dir: !path ../../../models/qwen2-reranker-0420
  processor:
    (): LLM4IR.utils.transformers_wrappers.AllPurposeWrapper
    class_to_instanciate: !ext LLM4IR.models.MonoQwen2Processor
    pretrained_model_name_or_path:  "./model/Qwen2-VL-2B-Instruct"
    num_image_tokens: 4096
    # max_length: 50
  trainer : !ext LLM4IR.trainer.RerankerTrainer
  collator: !ext LLM4IR.collators.VisualRerankerCollator
  model:
    (): LLM4IR.utils.transformers_wrappers.AllPurposeWrapper
    class_to_instanciate: !ext LLM4IR.models.MonoQwen2
    pretrained_model_name_or_path: "./model/Qwen2-VL-2B-Instruct"
    torch_dtype:  !ext torch.bfloat16
    use_cache: false
    attn_implementation: "flash_attention_2"
#    device_map: "auto"
#    quantization_config:
#      (): transformers.BitsAndBytesConfig
#      load_in_4bit: true
#      bnb_4bit_quant_type: "nf4"
#      bnb_4bit_compute_dtype:  "bfloat16"
#      bnb_4bit_use_double_quant: true

  dataset_loading_func: !ext LLM4IR.dataset.dataset_transformation.load_train_set_detailed
  eval_dataset_loader: !import ../data/beir_debug_data.yaml

  # max_length: 50
  neg_num: 2
  use_example: False
  run_train: True
  run_eval: False
  # pretrained_peft_model_name_or_path: './models/colqwen2-sparse-test0223'

  loss_func:
    (): LLM4IR.loss.reranker_losses.CERerankerLoss
  tr_args:
    (): transformers.training_args.TrainingArguments
    output_dir: null
    overwrite_output_dir: true
    num_train_epochs: 3
    per_device_train_batch_size: 16
    gradient_checkpointing: true
    gradient_checkpointing_kwargs: { "use_reentrant": false}
    # gradient_checkpointing: true
    # 6 x 8 gpus = 48 batch size
    # gradient_accumulation_steps: 4
    per_device_eval_batch_size: 3
    eval_strategy: "steps"
    dataloader_num_workers: 4
    # bf16: true
    save_steps: 200
    logging_steps: 10
    eval_steps: 200
    warmup_steps: 100
    learning_rate: 3e-4
    save_total_limit: 3
    # resume_from_checkpoint: true
    # optim: "paged_adamw_8bit"
    # wandb logging
    # wandb_project: "reanker_qwen2"
    # run_name: "reranker_qwen2"
    report_to: "wandb"

  peft_config:
    (): peft.LoraConfig
    r: 32
    lora_alpha: 32
    lora_dropout: 0.1
    init_lora_weights: "gaussian"
    bias: "none"
    task_type: "FEATURE_EXTRACTION"
    target_modules: '(.*(model).*(down_proj|gate_proj|up_proj|k_proj|q_proj|v_proj|o_proj).*$|.*(lm_head).*$)'
    # target_modules: '(.*(model).*(down_proj|gate_proj|up_proj|k_proj|q_proj|v_proj|o_proj).*$|.*(custom_text_proj).*$)'
    # target_modules: '(.*(language_model).*(down_proj|gate_proj|up_proj|k_proj|q_proj|v_proj|o_proj).*$|.*(custom_text_proj).*$)'

